# Generated by Django 4.2.6 on 2023-10-09 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UserID',
            new_name='user_id',
        ),
    ]
