# Generated by Django 4.2.6 on 2023-10-11 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_userid_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='UserID',
        ),
    ]
