# Generated by Django 4.2.6 on 2023-10-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_user_id_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
