# Generated by Django 4.2.6 on 2023-10-09 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_Role',
            fields=[
                ('RoleName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('AssignDate', models.DateField()),
                ('LeaderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leader.leader')),
            ],
        ),
    ]
