# Generated by Django 4.2.6 on 2023-10-11 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0002_remove_leader_userid_leader_user_ptr'),
        ('user', '0002_rename_userid_user_user_id'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='user.user')),
                ('MemberID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=100)),
                ('AssignDate', models.DateField()),
                ('LeaderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leader.leader')),
            ],
            bases=('user.user',),
        ),
        migrations.DeleteModel(
            name='Member_Role',
        ),
    ]
