# Generated by Django 4.2.6 on 2023-10-09 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('TaskId', models.AutoField(primary_key=True, serialize=False)),
                ('TaskName', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Status', models.BooleanField()),
                ('Priority', models.CharField(max_length=255)),
                ('DueDate', models.DateField()),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
