# Generated by Django 4.2.6 on 2023-10-11 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_userid_user_user_id'),
        ('leader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='UserID',
        ),
        migrations.AddField(
            model_name='leader',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True,on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='user.user'),
            preserve_default=False,
        ),
    ]
