# Generated by Django 4.2.6 on 2023-10-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0004_alter_leader_leaderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='LeaderID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
